name: nodeWorkflow
on: push
jobs:
  checkJob:
    runs-on: ubuntu-latest
    steps:
      - name: cloneRepo
        uses: actions/checkout@v4
      - name: cloneNodeSource
        uses: actions/setup-node@v4
      - name: installNmp
        run: npm install
      - name: setupApp
        run: make setup
      - name: testApp
        run: make test
      - name: runLint
        run: make lint
      - name: customeAction
        uses: actions/javascript-action@v1
